#!/bin/bash -xe
GOOGLE_ACCESS_KEY=$1
CONNECTION_STRING=$2


GOOGLE_ACCESS_SECRET_NAME="googleaccesskey"
GOOGLE_ACCESS_SECRET_STRING="{\"apikey\":\"${GOOGLE_ACCESS_KEY}\"}"
GOOGLE_ACCESS_RESP=$(aws secretsmanager update-secret \
    --secret-id $GOOGLE_ACCESS_SECRET_NAME \
    --description "Access key for google services"
    --secret-string $GOOGLE_ACCESS_SECRET_STRING)

CONNECTION_STRING_SECRET_NAME="covidrds"
CONNECTION_STRING_SECRET_STRING="{\"connectionstring\":\"${CONNECTION_STRING}\"}"
CONNECTION_STRING_RESP=$(aws secretsmanager update-secret \
    --secret-id $CONNECTION_STRING_SECRET_NAME \
    --description "Connection string to Covid19 RDS"
    --secret-string $CONNECTION_STRING_SECRET_STRING)